### ISSUE TITLE
Interfaces don't play well with @overload

### ISSUE THREAD

**Issue by wiml** [Shoobx/mypy-zope#46]
They sort of work, in that calls to `@overload`ed functions of an interface type are typechecked correctly, but there are two problems:

* Mypy produces errors like `error: Self argument missing for a non-static method (or an invalid type for self)`
* I haven't been able to declare a class that implements an interface with an overloaded method without getting a mypy error like `error: Signature of "MySomething" incompatible with "getStuff" of supertype "ISomething"`.

[Here's a gist](https://gist.github.com/wiml/5434a9e49699d5238034202cb123184d) demonstrating the situation I'm talking about.

Interestingly, the actual *uses* of both the interface and the concrete class seem to be typechecked correctly at least some of the time: the assignments to variables `i` and `j` are satisfactory to mypy, even though they wouldn't be without the `@overload`s.

(Using mypy==0.812 mypy-extensions==0.4.3 mypy-zope==0.2.13 )

**Comment by kedder** [comment]
Things like this are tricky. Zope interfaces are very unusual, but with some dedication it might be possible to get this one supported. 

The second message is produced by mypy-zope. We check the signature of a function against the interface manually, so maybe we need a special support for `@overload` there. Or, `@overload` might not be registered properly because of the first message.

The first one is the message of mypy itself. Normally we work around it by inserting "self" parameter to class definition when interface is encountered, but I guess in this case the error produced before this "modification".

**Comment by kedder** [comment]
This will be fixed in the next release (via #48)
